In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import interpolate

In [17]:
df = pd.read_csv('pytrends_100.csv', index_col = 'Datetime')

df.head()

,M1,M2,M3,M4,M5,M6,M6(T),M8,M9,M11,...,M90,M180,M181,M271,M275,M602,M606,M621,M876,M898
Datetime,,,,,,,,,,,,,,,,,,,,,
26/02/2018 00:00,4,0,0,0.8,1.6,7.200000,7.200000,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0.0,0
26/02/2018 01:00,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0.0,0
26/02/2018 02:00,2,0,0,0.0,2.0,42.000000,21.000000,2.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0.0,0
26/02/2018 03:00,2,0,0,0.0,2.0,32.666667,2.000000,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0.0,0,0.0,0
26/02/2018 04:00,2,0,0,0.0,0.0,51.333333,9.333333,0.0,0.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0,0.0,0

In [18]:
index = pd.date_range("2018/02/26 00:00:00", "2018/03/05 23:00:00", freq = "1H")
df["date"]=index
df

,M1,M2,M3,M4,M5,M6,M6(T),M8,M9,M11,...,M180,M181,M271,M275,M602,M606,M621,M876,M898,date
Datetime,,,,,,,,,,,,,,,,,,,,,
26/02/2018 00:00,4,0,0,0.800000,1.600000,7.200000,7.200000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 00:00:00
26/02/2018 01:00,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 01:00:00
26/02/2018 02:00,2,0,0,0.000000,2.000000,42.000000,21.000000,2.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 02:00:00
26/02/2018 03:00,2,0,0,0.000000,2.000000,32.666667,2.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 03:00:00
26/02/2018 04:00,2,0,0,0.000000,0.000000,51.333333,9.333333,0.000000,0.000000,2.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 04:00:00
26/02/2018 05:00,3,0,0,9.750000,3.000000,23.250000,16.500000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 05:00:00
26/02/2018 06:00,4,0,1,1.600000,1.600000,29.600000,18.400000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 06:00:00
26/02/2018 07:00,6,1,0,1.000000,2.000000,26.000000,13.000000,0.000000,0.600000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 07:00:00
26/02/2018 08:00,3,1,0,1.500000,1.500000,13.500000,11.250000,0.000000,0.000000,0.600000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 08:00:00
26/02/2018 09:00,2,0,1,0.666667,0.666667,10.666667,8.000000,0.000000,0.000000,0.500000,...,0.5,0,0,0,0,0.0,0,0.0,0,2018-02-26 09:00:00
26/02/2018 10:00,3,1,1,1.000000,1.000000,13.000000,12.000000,0.000000,0.000000,0.600000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 10:00:00
26/02/2018 11:00,3,1,1,2.000000,0.000000,8.000000,9.000000,0.000000,0.000000,0.750000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 11:00:00
26/02/2018 12:00,3,1,0,2.000000,1.000000,7.000000,8.000000,0.000000,0.000000,0.750000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 12:00:00
26/02/2018 13:00,4,1,1,1.000000,1.000000,6.000000,10.000000,0.000000,0.000000,0.666667,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 13:00:00
26/02/2018 14:00,2,0,0,2.000000,1.000000,3.000000,8.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 14:00:00
26/02/2018 15:00,3,1,0,2.250000,0.750000,4.500000,8.250000,0.000000,0.000000,0.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 15:00:00
26/02/2018 16:00,2,1,0,0.666667,0.000000,2.000000,5.333333,0.000000,0.000000,0.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 16:00:00
26/02/2018 17:00,2,0,1,2.000000,3.000000,5.000000,9.000000,0.000000,0.500000,0.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 17:00:00
26/02/2018 18:00,4,1,1,2.000000,2.000000,5.000000,7.000000,0.000000,0.000000,0.666667,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 18:00:00
26/02/2018 19:00,2,1,1,0.666667,0.666667,2.000000,4.666667,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 19:00:00
26/02/2018 20:00,4,1,0,1.000000,1.000000,2.000000,5.000000,0.666667,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 20:00:00
26/02/2018 21:00,3,2,0,1.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 21:00:00
26/02/2018 22:00,4,2,0,2.000000,1.000000,4.000000,7.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 22:00:00
26/02/2018 23:00,4,1,1,0.800000,1.600000,2.400000,3.200000,0.000000,0.000000,1.142857,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-26 23:00:00
27/02/2018 00:00,1,4,0,0.000000,0.000000,1.000000,7.000000,0.000000,0.000000,0.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 00:00:00
27/02/2018 01:00,2,0,0,2.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 01:00:00
27/02/2018 02:00,3,2,0,1.500000,0.000000,3.000000,0.000000,0.000000,0.000000,1.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 02:00:00
27/02/2018 03:00,7,4,2,5.000000,5.000000,2.000000,5.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 03:00:00
27/02/2018 04:00,17,15,2,4.250000,4.250000,14.450000,4.250000,0.000000,0.000000,4.533333,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 04:00:00
27/02/2018 05:00,21,23,0,3.500000,0.875000,30.625000,8.750000,1.166667,0.000000,2.916667,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-02-27 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
04/03/2018 18:00,2,0,0,1.000000,1.000000,4.000000,5.000000,0.666667,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 18:00:00
04/03/2018 19:00,2,0,1,1.000000,1.000000,2.000000,5.000000,0.666667,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 19:00:00
04/03/2018 20:00,1,0,0,0.000000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 20:00:00
04/03/2018 21:00,1,0,0,0.500000,0.500000,1.000000,2.000000,0.500000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 21:00:00
04/03/2018 22:00,2,0,0,1.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 22:00:00
04/03/2018 23:00,1,0,1,0.000000,0.500000,1.000000,1.500000,0.000000,0.000000,0.500000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-04 23:00:00
05/03/2018 00:00,2,0,1,1.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 00:00:00
05/03/2018 01:00,1,0,0,2.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 01:00:00
05/03/2018 02:00,1,0,0,0.000000,0.000000,0.000000,1.500000,0.000000,0.000000,1.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 02:00:00
05/03/2018 03:00,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 03:00:00
05/03/2018 04:00,6,2,0,0.000000,1.714286,1.714286,4.285714,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 04:00:00
05/03/2018 05:00,3,0,3,7.000000,2.000000,3.000000,10.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 05:00:00
05/03/2018 06:00,3,0,0,0.750000,1.500000,0.000000,7.500000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 06:00:00
05/03/2018 07:00,2,0,1,0.000000,1.000000,4.000000,10.000000,0.666667,0.666667,0.666667,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 07:00:00
05/03/2018 08:00,2,0,0,2.000000,2.000000,3.333333,6.666667,1.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 08:00:00
05/03/2018 09:00,2,0,0,3.000000,2.000000,4.000000,9.000000,1.333333,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 09:00:00
05/03/2018 10:00,3,0,0,3.000000,0.000000,3.000000,8.000000,0.750000,0.000000,0.750000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 10:00:00
05/03/2018 11:00,1,0,0,4.000000,1.000000,2.000000,9.000000,0.500000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 11:00:00
05/03/2018 12:00,3,0,0,3.000000,1.000000,3.000000,8.000000,0.600000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 12:00:00
05/03/2018 13:00,2,0,0,3.000000,2.000000,2.000000,7.000000,0.666667,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 13:00:00
05/03/2018 14:00,3,0,0,3.750000,1.500000,2.250000,6.000000,0.500000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 14:00:00
05/03/2018 15:00,2,0,0,5.000000,0.000000,2.000000,7.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 15:00:00
05/03/2018 16:00,2,0,0,5.000000,1.000000,2.000000,7.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 16:00:00
05/03/2018 17:00,2,0,0,6.000000,0.000000,2.000000,6.000000,0.666667,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 17:00:00
05/03/2018 18:00,1,0,0,2.000000,0.000000,2.000000,4.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 18:00:00
05/03/2018 19:00,1,0,0,0.500000,0.500000,1.000000,2.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 19:00:00
05/03/2018 20:00,2,0,0,1.000000,1.000000,2.000000,5.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 20:00:00
05/03/2018 21:00,2,0,0,1.000000,1.000000,2.000000,4.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 21:00:00
05/03/2018 22:00,2,0,0,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,...,0.0,0,0,0,0,0.0,0,0.0,0,2018-03-05 22:00:00
05/03/2018 23:00,2,0,0,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,...,0.5,0,0,0,0,0.0,0,0.0,0,2018-03-05 23:00:00

In [19]:
index = pd.date_range("2018/02/26 00:00:00", "2018/03/05 23:45:00", freq = "15min")
d = {"date": index}
new_Data = pd.DataFrame(d)
new_Data = new_Data.merge(df, how = "left", left_on = "date", right_on = "date")
new_Data = new_Data.interpolate()
new_Data

,date,M1,M2,M3,M4,M5,M6,M6(T),M8,M9,...,M90,M180,M181,M271,M275,M602,M606,M621,M876,M898
0,2018-02-26 00:00:00,4.00,0.00,0.00,0.8000,1.600,7.200000,7.200000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018-02-26 00:15:00,3.00,0.00,0.00,0.6000,1.200,5.400000,5.400000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018-02-26 00:30:00,2.00,0.00,0.00,0.4000,0.800,3.600000,3.600000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018-02-26 00:45:00,1.00,0.00,0.00,0.2000,0.400,1.800000,1.800000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018-02-26 01:00:00,0.00,0.00,0.00,0.0000,0.000,0.000000,0.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2018-02-26 01:15:00,0.50,0.00,0.00,0.0000,0.500,10.500000,5.250000,0.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2018-02-26 01:30:00,1.00,0.00,0.00,0.0000,1.000,21.000000,10.500000,1.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2018-02-26 01:45:00,1.50,0.00,0.00,0.0000,1.500,31.500000,15.750000,1.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2018-02-26 02:00:00,2.00,0.00,0.00,0.0000,2.000,42.000000,21.000000,2.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2018-02-26 02:15:00,2.00,0.00,0.00,0.0000,2.000,39.666667,16.250000,1.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2018-02-26 02:30:00,2.00,0.00,0.00,0.0000,2.000,37.333333,11.500000,1.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2018-02-26 02:45:00,2.00,0.00,0.00,0.0000,2.000,35.000000,6.750000,0.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2018-02-26 03:00:00,2.00,0.00,0.00,0.0000,2.000,32.666667,2.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2018-02-26 03:15:00,2.00,0.00,0.00,0.0000,1.500,37.333333,3.833333,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2018-02-26 03:30:00,2.00,0.00,0.00,0.0000,1.000,42.000000,5.666667,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2018-02-26 03:45:00,2.00,0.00,0.00,0.0000,0.500,46.666667,7.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2018-02-26 04:00:00,2.00,0.00,0.00,0.0000,0.000,51.333333,9.333333,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2018-02-26 04:15:00,2.25,0.00,0.00,2.4375,0.750,44.312500,11.125000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2018-02-26 04:30:00,2.50,0.00,0.00,4.8750,1.500,37.291667,12.916667,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2018-02-26 04:45:00,2.75,0.00,0.00,7.3125,2.250,30.270833,14.708333,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2018-02-26 05:00:00,3.00,0.00,0.00,9.7500,3.000,23.250000,16.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2018-02-26 05:15:00,3.25,0.00,0.25,7.7125,2.650,24.837500,16.975000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2018-02-26 05:30:00,3.50,0.00,0.50,5.6750,2.300,26.425000,17.450000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2018-02-26 05:45:00,3.75,0.00,0.75,3.6375,1.950,28.012500,17.925000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2018-02-26 06:00:00,4.00,0.00,1.00,1.6000,1.600,29.600000,18.400000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2018-02-26 06:15:00,4.50,0.25,0.75,1.4500,1.700,28.700000,17.050000,0.000000,0.15,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2018-02-26 06:30:00,5.00,0.50,0.50,1.3000,1.800,27.800000,15.700000,0.000000,0.30,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2018-02-26 06:45:00,5.50,0.75,0.25,1.1500,1.900,26.900000,14.350000,0.000000,0.45,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2018-02-26 07:00:00,6.00,1.00,0.00,1.0000,2.000,26.000000,13.000000,0.000000,0.60,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2018-02-26 07:15:00,5.25,1.00,0.00,1.1250,1.875,22.875000,12.562500,0.000000,0.45,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,2018-03-05 16:30:00,2.00,0.00,0.00,5.5000,0.500,2.000000,6.500000,0.333333,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
739,2018-03-05 16:45:00,2.00,0.00,0.00,5.7500,0.250,2.000000,6.250000,0.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
740,2018-03-05 17:00:00,2.00,0.00,0.00,6.0000,0.000,2.000000,6.000000,0.666667,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
741,2018-03-05 17:15:00,1.75,0.00,0.00,5.0000,0.000,2.000000,5.500000,0.500000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
742,2018-03-05 17:30:00,1.50,0.00,0.00,4.0000,0.000,2.000000,5.000000,0.333333,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
743,2018-03-05 17:45:00,1.25,0.00,0.00,3.0000,0.000,2.000000,4.500000,0.166667,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
744,2018-03-05 18:00:00,1.00,0.00,0.00,2.0000,0.000,2.000000,4.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
745,2018-03-05 18:15:00,1.00,0.00,0.00,1.6250,0.125,1.750000,3.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
746,2018-03-05 18:30:00,1.00,0.00,0.00,1.2500,0.250,1.500000,3.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
747,2018-03-05 18:45:00,1.00,0.00,0.00,0.8750,0.375,1.250000,2.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
748,2018-03-05 19:00:00,1.00,0.00,0.00,0.5000,0.500,1.000000,2.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
749,2018-03-05 19:15:00,1.25,0.00,0.00,0.6250,0.625,1.250000,2.750000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
750,2018-03-05 19:30:00,1.50,0.00,0.00,0.7500,0.750,1.500000,3.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
751,2018-03-05 19:45:00,1.75,0.00,0.00,0.8750,0.875,1.750000,4.250000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
752,2018-03-05 20:00:00,2.00,0.00,0.00,1.0000,1.000,2.000000,5.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
753,2018-03-05 20:15:00,2.00,0.00,0.00,1.0000,1.000,2.000000,4.750000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
754,2018-03-05 20:30:00,2.00,0.00,0.00,1.0000,1.000,2.000000,4.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,2018-03-05 20:45:00,2.00,0.00,0.00,1.0000,1.000,2.000000,4.250000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
756,2018-03-05 21:00:00,2.00,0.00,0.00,1.0000,1.000,2.000000,4.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
757,2018-03-05 21:15:00,2.00,0.00,0.00,1.0000,1.000,1.750000,3.750000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
758,2018-03-05 21:30:00,2.00,0.00,0.00,1.0000,1.000,1.500000,3.500000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
759,2018-03-05 21:45:00,2.00,0.00,0.00,1.0000,1.000,1.250000,3.250000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
760,2018-03-05 22:00:00,2.00,0.00,0.00,1.0000,1.000,1.000000,3.000000,0.000000,0.00,...,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761,2018-03-05 22:15:00,2.00,0.00,0.00,0.7500,1.000,0.750000,2.750000,0.000000,0.00,...,0.0,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
762,2018-03-05 22:30:00,2.00,0.00,0.00,0.5000,1.000,0.500000,2.500000,0.000000,0.00,...,0.0,0.250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
763,2018-03-05 22:45:00,2.00,0.00,0.00,0.2500,1.000,0.250000,2.250000,0.000000,0.00,...,0.0,0.375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
764,2018-03-05 23:00:00,2.00,0.00,0.00,0.0000,1.000,0.000000,2.000000,0.000000,0.00,...,0.0,0.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
765,2018-03-05 23:15:00,2.00,0.00,0.00,0.0000,1.000,0.000000,2.000000,0.000000,0.00,...,0.0,0.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
766,2018-03-05 23:30:00,2.00,0.00,0.00,0.0000,1.000,0.000000,2.000000,0.000000,0.00,...,0.0,0.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
767,2018-03-05 23:45:00,2.00,0.00,0.00,0.0000,1.000,0.000000,2.000000,0.000000,0.00,...,0.0,0.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
new_Data1 = new_Data.melt(id_vars=['date'])

In [21]:
new_Data1

                     date variable  value
0     2018-02-26 00:00:00       M1   4.00
1     2018-02-26 00:15:00       M1   3.00
2     2018-02-26 00:30:00       M1   2.00
3     2018-02-26 00:45:00       M1   1.00
4     2018-02-26 01:00:00       M1   0.00
5     2018-02-26 01:15:00       M1   0.50
6     2018-02-26 01:30:00       M1   1.00
7     2018-02-26 01:45:00       M1   1.50
8     2018-02-26 02:00:00       M1   2.00
9     2018-02-26 02:15:00       M1   2.00
10    2018-02-26 02:30:00       M1   2.00
11    2018-02-26 02:45:00       M1   2.00
12    2018-02-26 03:00:00       M1   2.00
13    2018-02-26 03:15:00       M1   2.00
14    2018-02-26 03:30:00       M1   2.00
15    2018-02-26 03:45:00       M1   2.00
16    2018-02-26 04:00:00       M1   2.00
17    2018-02-26 04:15:00       M1   2.25
18    2018-02-26 04:30:00       M1   2.50
19    2018-02-26 04:45:00       M1   2.75
20    2018-02-26 05:00:00       M1   3.00
21    2018-02-26 05:15:00       M1   3.25
22    2018-02-26 05:30:00       M1   3.50
23    2018-02-26 05:45:00       M1   3.75
24    2018-02-26 06:00:00       M1   4.00
25    2018-02-26 06:15:00       M1   4.50
26    2018-02-26 06:30:00       M1   5.00
27    2018-02-26 06:45:00       M1   5.50
28    2018-02-26 07:00:00       M1   6.00
29    2018-02-26 07:15:00       M1   5.25
...                   ...      ...    ...
38370 2018-03-05 16:30:00     M898   0.00
38371 2018-03-05 16:45:00     M898   0.00
38372 2018-03-05 17:00:00     M898   0.00
38373 2018-03-05 17:15:00     M898   0.00
38374 2018-03-05 17:30:00     M898   0.00
38375 2018-03-05 17:45:00     M898   0.00
38376 2018-03-05 18:00:00     M898   0.00
38377 2018-03-05 18:15:00     M898   0.00
38378 2018-03-05 18:30:00     M898   0.00
38379 2018-03-05 18:45:00     M898   0.00
38380 2018-03-05 19:00:00     M898   0.00
38381 2018-03-05 19:15:00     M898   0.00
38382 2018-03-05 19:30:00     M898   0.00
38383 2018-03-05 19:45:00     M898   0.00
38384 2018-03-05 20:00:00     M898   0.00
38385 2018-03-05 20:15:00     M898   0.00
38386 2018-03-05 20:30:00     M898   0.00
38387 2018-03-05 20:45:00     M898   0.00
38388 2018-03-05 21:00:00     M898   0.00
38389 2018-03-05 21:15:00     M898   0.00
38390 2018-03-05 21:30:00     M898   0.00
38391 2018-03-05 21:45:00     M898   0.00
38392 2018-03-05 22:00:00     M898   0.00
38393 2018-03-05 22:15:00     M898   0.00
38394 2018-03-05 22:30:00     M898   0.00
38395 2018-03-05 22:45:00     M898   0.00
38396 2018-03-05 23:00:00     M898   0.00
38397 2018-03-05 23:15:00     M898   0.00
38398 2018-03-05 23:30:00     M898   0.00
38399 2018-03-05 23:45:00     M898   0.00

[38400 rows x 3 columns]

In [22]:
new_Data1.to_csv('datetime_pytrends_100.csv')